##############################################
# Enhanced Mean Reversion Strategy Configuration
# Phase 1: Dynamic Stop-Loss and Time-Based Exits
##############################################

# Core parameters
initial_capital: 100000
max_positions: 10

# Mean Reversion Parameters
mean_reversion_params:
  # Signal Generation Parameters (from hybrid configuration)
  bb_period: 20
  bb_std_dev: 2.0
  rsi_period: 14
  rsi_overbought: 70
  rsi_oversold: 30
  require_reversal: true
  min_reversal_candles: 1
  
  # Enhanced Risk Management Parameters
  stop_loss_atr: 1.8  # Base ATR multiplier for stop loss
  take_profit_atr: 3.0  # ATR multiplier for take profit
  max_holding_days: 10  # Maximum number of days to hold a position
  
  # New Dynamic Stop-Loss Parameters
  use_support_resistance: true  # Use support/resistance levels for stop-loss placement
  support_lookback: 30  # Number of days to look back for support/resistance levels
  max_support_levels: 3  # Maximum number of support/resistance levels to consider

# Position Sizing Configuration
position_sizing_config:
  base_risk_per_trade: 0.01  # Risk 1% of equity per trade
  max_position_size: 0.1  # Maximum position size as a fraction of equity
  min_position_size: 0.005  # Minimum position size as a fraction of equity

# Trading Universe
symbols:
  # Stocks
  - symbol: AAPL
    weight: 1.2
  - symbol: MSFT
    weight: 1.2
  - symbol: GOOGL
    weight: 1.0
  - symbol: AMZN
    weight: 1.0
  - symbol: META
    weight: 1.0
  - symbol: NVDA
    weight: 1.3
  - symbol: AMD
    weight: 1.0
  - symbol: TSLA
    weight: 0.8
  - symbol: JPM
    weight: 1.0
  - symbol: DIS
    weight: 1.0
  - symbol: NFLX
    weight: 1.0
  - symbol: INTC
    weight: 0.8
  - symbol: CSCO
    weight: 1.0
  - symbol: ADBE
    weight: 1.0
  - symbol: PYPL
    weight: 0.8
  - symbol: CRM
    weight: 1.0
  - symbol: COST
    weight: 1.0
  - symbol: PEP
    weight: 1.0
  - symbol: CMCSA
    weight: 0.8
  - symbol: AVGO
    weight: 1.0
  - symbol: TXN
    weight: 1.0
  - symbol: QCOM
    weight: 1.0
  - symbol: TMUS
    weight: 1.0
  - symbol: IBM
    weight: 0.8
  - symbol: SBUX
    weight: 1.0
  
  # Cryptocurrencies
  - symbol: BTC/USD
    weight: 1.2
  - symbol: ETH/USD
    weight: 1.2
  - symbol: SOL/USD
    weight: 1.0
  - symbol: ADA/USD
    weight: 0.8
  - symbol: DOT/USD
    weight: 0.8
  - symbol: AVAX/USD
    weight: 1.0
  - symbol: LINK/USD
    weight: 1.0
  - symbol: MATIC/USD
    weight: 0.8
  - symbol: XRP/USD
    weight: 0.8
  - symbol: DOGE/USD
    weight: 0.6
  - symbol: UNI/USD
    weight: 0.8
  - symbol: AAVE/USD
    weight: 0.8
  - symbol: ATOM/USD
    weight: 0.8
  - symbol: LTC/USD
    weight: 0.8
  - symbol: BCH/USD
    weight: 0.8
  - symbol: XLM/USD
    weight: 0.8
  - symbol: EOS/USD
    weight: 0.6
  - symbol: FIL/USD
    weight: 0.8
  - symbol: ALGO/USD
    weight: 0.8
  - symbol: XTZ/USD
    weight: 0.8
  - symbol: COMP/USD
    weight: 0.8
  - symbol: MKR/USD
    weight: 0.8
  - symbol: YFI/USD
    weight: 0.8
  - symbol: SNX/USD
    weight: 0.6
  - symbol: SUSHI/USD
    weight: 0.6

# Visualization and Reporting
save_equity_curve: true
