# Mean Reversion Strategy Configuration for Backtesting

# General backtest settings
general:
  symbols: ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META', 'NVDA', 'TSLA', 'JPM', 'BAC', 'XLF', 'XLK', 'XLE', 'XLU', 'XLB']
  timeframe: '1D'
  initial_capital: 100000
  position_size_pct: 0.1
  max_positions: 8
  backtest_start_date: '2023-01-01'
  backtest_end_date: '2024-03-01'
  log_level: 'INFO'

# Strategy-specific configurations
strategies:
  MeanReversion:
    # Core parameters - taking the best from both configurations
    bb_period: 20
    bb_std_dev: 1.9  # Between Optimized (1.8) and Variant (2.0)
    rsi_period: 14
    rsi_overbought: 65  # Less extreme threshold for more signals
    rsi_oversold: 35  # Less extreme threshold for more signals
    
    # Signal generation parameters - from Variant which had better profit factor
    require_reversal: true  # Require reversal pattern for higher quality signals
    min_reversal_candles: 1  # Only need 1 candle for reversal
    
    # Risk management parameters - optimized for better risk-reward
    stop_loss_atr: 1.8  # 1.8x ATR for stop loss (slightly tighter than before)
    take_profit_atr: 3.0  # 3x ATR for take profit (1.67:1 risk-reward)
    
    # Position sizing parameters
    max_position_size: 0.1  # Maximum 10% of portfolio per position
    
    # Strategy weight in multi-strategy system
    base_weight: 0.35  # Higher weight due to good signal generation
    
    # Market regime detection parameters
    use_regime_filter: true
    min_regime_score: 0.3
    regime_filter_strength: 1.0
    
    # ML signal quality parameters
    use_ml_filter: true
    min_quality_score: 0.4
    ml_filter_strength: 1.0

  VolatilityBreakout:
    # Keep existing parameters
    base_weight: 0.2

  TrendFollowing:
    # Keep existing parameters
    base_weight: 0.25

  GapTrading:
    # Keep existing parameters
    base_weight: 0.2

# Global settings
global:
  max_open_positions: 5
  max_positions_per_symbol: 2
  max_correlated_positions: 3
  correlation_threshold: 0.7
  max_portfolio_risk: 0.02  # Maximum 2% portfolio risk per day
  default_position_size: 0.05  # Default 5% of portfolio per position
  
# Stock-specific configurations - optimized based on performance analysis
stocks:
  AAPL:
    position_size: 0.08
    strategies:
      MeanReversion:
        weight_multiplier: 1.3  # Increased based on strong performance
  MSFT:
    position_size: 0.08
    strategies:
      MeanReversion:
        weight_multiplier: 1.2
  GOOGL:
    position_size: 0.07
    strategies:
      MeanReversion:
        weight_multiplier: 1.1
  AMZN:
    position_size: 0.07
    strategies:
      MeanReversion:
        weight_multiplier: 1.1
  META:
    position_size: 0.07
    strategies:
      MeanReversion:
        weight_multiplier: 1.4  # Increased based on strong performance

# Market regime detection parameters
market_regime_params:
  short_ma_period: 20
  medium_ma_period: 50
  long_ma_period: 200
  trend_threshold: 0.02
  volatility_period: 20
  high_volatility_threshold: 0.015
  low_volatility_threshold: 0.008
  adx_period: 14
  adx_threshold: 25
  regime_change_lookback: 5

# ML signal classifier parameters
ml_classifier_params:
  model_type: random_forest
  feature_lookback: 20
  min_train_samples: 100
  model_path: models/signal_classifier.pkl
  retrain_frequency: 30
