# Enhanced Seasonality Strategy Configuration

# General settings
name: "Enhanced Seasonality Strategy"
description: "Combined strategy with enhanced seasonality integration for better stock selection"
version: "1.0.0"

# Backtest settings
backtest:
  initial_capital: 100000
  start_date: "2023-01-01"
  end_date: "2023-12-31"
  symbols:
    - "SPY"
    - "QQQ"
    - "AAPL"
    - "MSFT"
    - "AMZN"
    - "GOOGL"
    - "TSLA"
    - "NVDA"
    - "AMD"
    - "META"
    - "JPM"
    - "JNJ"
    - "PFE"
    - "WMT"
    - "XOM"
  timeframe: "1D"

# Strategy weights
strategy_weights:
  mean_reversion: 0.5
  trend_following: 0.5

# Dynamic weight adjustment
dynamic_weights:
  enabled: true
  market_regime_weights:
    trending:
      mean_reversion: 0.2
      trend_following: 0.8
    range_bound:
      mean_reversion: 0.8
      trend_following: 0.2
    mixed:
      mean_reversion: 0.5
      trend_following: 0.5
    unknown:
      mean_reversion: 0.5
      trend_following: 0.5

# Enhanced seasonality settings
seasonality:
  enabled: true
  data_file: "data/seasonality.yaml"
  min_score_threshold: 0.6
  weight_adjustment: true
  sector_influence: 0.3
  stock_specific_influence: 0.7
  top_n_selection: 5

# Mean Reversion Strategy
mean_reversion:
  # Bollinger Bands parameters
  bb_period: 20
  bb_std: 1.9
  
  # RSI parameters
  rsi_period: 14
  rsi_oversold: 35
  rsi_overbought: 65
  
  # Signal confirmation
  require_reversal: true
  volume_filter: true
  
  # Risk management
  stop_loss_atr: 1.8
  take_profit_atr: 3.0
  atr_period: 14
  
  # Position sizing
  max_position_size: 0.05
  position_sizing_method: "volatility"
  
  # Symbol-specific weights
  symbol_weights:
    AAPL: 1.2
    MSFT: 1.1
    AMZN: 1.0
    GOOGL: 1.0
    TSLA: 0.8
    NVDA: 1.3
    AMD: 1.2
    META: 1.0
    JPM: 0.9
    JNJ: 1.1
    PFE: 0.9
    WMT: 1.0
    XOM: 0.8

# Trend Following Strategy
trend_following:
  # Moving Average parameters
  fast_ema: 9
  slow_ema: 21
  
  # MACD parameters
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  
  # ADX parameters
  adx_period: 14
  adx_threshold: 25
  
  # Confirmation indicators
  use_volume_confirmation: true
  use_momentum_confirmation: true
  
  # Risk management
  stop_loss_atr: 2.0
  take_profit_atr: 4.0
  atr_period: 14
  
  # Position sizing
  max_position_size: 0.05
  position_sizing_method: "volatility"
  
  # Symbol-specific weights
  symbol_weights:
    AAPL: 1.0
    MSFT: 1.1
    AMZN: 1.2
    GOOGL: 1.1
    TSLA: 1.3
    NVDA: 1.4
    AMD: 1.3
    META: 1.2
    JPM: 0.8
    JNJ: 0.7
    PFE: 0.7
    WMT: 0.8
    XOM: 0.9

# Risk Management
risk_management:
  max_open_positions: 5
  max_portfolio_risk: 0.02
  position_size_limit: 0.1
  stop_loss_required: true
