# Configuration for Enhanced Multi-Factor Strategy with 200 Stocks

# General settings
general:
  log_level: INFO
  initial_capital: 100000
  max_positions: 20  # Increased to handle more stocks
  max_portfolio_risk_pct: 0.02
  min_capital_per_trade: 1000
  symbols:
    # Major Indices
    - SPY  # S&P 500
    - QQQ  # Nasdaq 100
    - DIA  # Dow Jones
    - IWM  # Russell 2000
    # Technology
    - AAPL  # Apple
    - MSFT  # Microsoft
    - AMZN  # Amazon
    - GOOGL # Alphabet
    - META  # Meta Platforms
    - NVDA  # NVIDIA
    - AMD   # Advanced Micro Devices
    - INTC  # Intel
    - CSCO  # Cisco
    - ORCL  # Oracle
    - IBM   # IBM
    - ADBE  # Adobe
    - CRM   # Salesforce
    - PYPL  # PayPal
    - NFLX  # Netflix
    - TSLA  # Tesla
    - AVGO  # Broadcom
    - TXN   # Texas Instruments
    - QCOM  # Qualcomm
    - MU    # Micron Technology
    - AMAT  # Applied Materials
    - ADI   # Analog Devices
    - LRCX  # Lam Research
    - KLAC  # KLA Corporation
    - SNPS  # Synopsys
    - CDNS  # Cadence Design
    - INTU  # Intuit
    - NOW   # ServiceNow
    - WDAY  # Workday
    - TEAM  # Atlassian
    - ZS    # Zscaler
    - OKTA  # Okta
    - CRWD  # CrowdStrike
    - NET   # Cloudflare
    - DDOG  # Datadog
    - SNOW  # Snowflake
    # Financial
    - JPM   # JPMorgan Chase
    - BAC   # Bank of America
    - WFC   # Wells Fargo
    - C     # Citigroup
    - GS    # Goldman Sachs
    - MS    # Morgan Stanley
    - BLK   # BlackRock
    - AXP   # American Express
    - V     # Visa
    - MA    # Mastercard
    - SCHW  # Charles Schwab
    - PNC   # PNC Financial
    - USB   # U.S. Bancorp
    - TFC   # Truist Financial
    - COF   # Capital One
    # Healthcare
    - JNJ   # Johnson & Johnson
    - PFE   # Pfizer
    - MRK   # Merck
    - ABBV  # AbbVie
    - LLY   # Eli Lilly
    - ABT   # Abbott Laboratories
    - TMO   # Thermo Fisher
    - DHR   # Danaher
    - UNH   # UnitedHealth
    - CVS   # CVS Health
    - AMGN  # Amgen
    - GILD  # Gilead Sciences
    - ISRG  # Intuitive Surgical
    - REGN  # Regeneron
    - VRTX  # Vertex Pharmaceuticals
    - MRNA  # Moderna
    - BIIB  # Biogen
    # Consumer
    - PG    # Procter & Gamble
    - KO    # Coca-Cola
    - PEP   # PepsiCo
    - WMT   # Walmart
    - COST  # Costco
    - HD    # Home Depot
    - LOW   # Lowe's
    - MCD   # McDonald's
    - SBUX  # Starbucks
    - NKE   # Nike
    - DIS   # Disney
    - CMCSA # Comcast
    - TGT   # Target
    - AMZN  # Amazon (repeated for consumer sector)
    - BKNG  # Booking Holdings
    - MAR   # Marriott
    - CMG   # Chipotle
    - YUM   # Yum! Brands
    - MDLZ  # Mondelez
    - EL    # Estée Lauder
    # Industrial
    - GE    # General Electric
    - HON   # Honeywell
    - MMM   # 3M
    - CAT   # Caterpillar
    - DE    # Deere
    - BA    # Boeing
    - LMT   # Lockheed Martin
    - RTX   # Raytheon
    - UPS   # UPS
    - FDX   # FedEx
    - UNP   # Union Pacific
    - CSX   # CSX Corporation
    - NSC   # Norfolk Southern
    - EMR   # Emerson Electric
    - ETN   # Eaton
    - ITW   # Illinois Tool Works
    - ROK   # Rockwell Automation
    # Energy
    - XOM   # Exxon Mobil
    - CVX   # Chevron
    - COP   # ConocoPhillips
    - EOG   # EOG Resources
    - SLB   # Schlumberger
    - PXD   # Pioneer Natural Resources
    - OXY   # Occidental Petroleum
    - PSX   # Phillips 66
    - VLO   # Valero Energy
    - MPC   # Marathon Petroleum
    # Utilities
    - NEE   # NextEra Energy
    - DUK   # Duke Energy
    - SO    # Southern Company
    - D     # Dominion Energy
    - AEP   # American Electric Power
    - XEL   # Xcel Energy
    - ED    # Consolidated Edison
    - EXC   # Exelon
    - PCG   # PG&E
    - SRE   # Sempra Energy
    # Real Estate
    - AMT   # American Tower
    - PLD   # Prologis
    - CCI   # Crown Castle
    - EQIX  # Equinix
    - PSA   # Public Storage
    - O     # Realty Income
    - AVB   # AvalonBay Communities
    - EQR   # Equity Residential
    - DLR   # Digital Realty
    - SPG   # Simon Property Group
    # Materials
    - LIN   # Linde
    - SHW   # Sherwin-Williams
    - APD   # Air Products
    - ECL   # Ecolab
    - FCX   # Freeport-McMoRan
    - NEM   # Newmont
    - NUE   # Nucor
    - DOW   # Dow Inc.
    - DD    # DuPont
    - ALB   # Albemarle
    # Communication Services
    - T     # AT&T
    - VZ    # Verizon
    - TMUS  # T-Mobile
    - CHTR  # Charter Communications
    - EA    # Electronic Arts
    - ATVI  # Activision Blizzard
    - TTWO  # Take-Two Interactive
    - MTCH  # Match Group
    - PINS  # Pinterest
    - SNAP  # Snap
    - TWTR  # Twitter (if still available)
    # Others
    - BRK.B # Berkshire Hathaway
    - PM    # Philip Morris
    - MO    # Altria
    - BIDU  # Baidu
    - BABA  # Alibaba
    - JD    # JD.com
    - PDD   # Pinduoduo
    - SHOP  # Shopify
    - SQ    # Block (Square)
    - UBER  # Uber
    - LYFT  # Lyft
    - ABNB  # Airbnb
    - DASH  # DoorDash
    - ZM    # Zoom
    - COIN  # Coinbase
    - PLTR  # Palantir
    - RBLX  # Roblox
    - U     # Unity Software
    - AI    # C3.ai
    - PATH  # UiPath
  timeframe: '1D'
  position_size_pct: 0.05  # Base position size (will be adjusted dynamically)
  backtest_start_date: '2023-01-01'
  backtest_end_date: '2023-03-31'
  min_signal_score: 0.55  # Minimum score to generate a signal

# Strategy-specific configurations
strategy_configs:
  # Mean Reversion Strategy parameters
  MeanReversion:
    weight: 0.45
    bb_period: 20
    bb_std: 1.9  # Using optimized value from previous testing
    rsi_period: 14
    rsi_lower: 35  # Using optimized value from previous testing
    rsi_upper: 65  # Using optimized value from previous testing
    require_reversal: true
    stop_loss_atr_multiplier: 1.8  # Using optimized value from previous testing
    take_profit_atr_multiplier: 3.0  # Using optimized value from previous testing
    atr_period: 14
    volume_filter: true
    volume_threshold: 1.5
    
  # Trend Following Strategy parameters
  TrendFollowing:
    weight: 0.45
    ema_short_period: 20
    ema_long_period: 50
    macd_fast_period: 12
    macd_slow_period: 26
    macd_signal_period: 9
    atr_period: 14
    stop_loss_atr_multiplier: 2.0
    take_profit_atr_multiplier: 4.0
    volume_filter: true
    volume_threshold: 1.5

# Market Regime Detection parameters
market_regime:
  adx_threshold: 25
  bb_width_change_threshold: 0.05
  lookback_period: 20
  trending_weight_adjustment: 0.2
  range_bound_weight_adjustment: 0.2

# Stock Selection parameters
stock_selection:
  enable_multi_factor: true
  technical_weight: 0.6
  seasonality_weight: 0.4
  top_n_stocks: 10  # Increased from 5 to 10 for more diversification
  min_technical_score: 0.6
  min_seasonality_score: 0.5
  
  # Technical factor weights
  technical_factors:
    momentum_weight: 0.3
    trend_weight: 0.3
    volatility_weight: 0.2
    volume_weight: 0.2
    
  # Regime-specific adjustments
  regime_adjustments:
    trending:
      trend_weight_multiplier: 1.5
      momentum_weight_multiplier: 1.2
      volatility_weight_multiplier: 0.8
      volume_weight_multiplier: 1.0
    range_bound:
      trend_weight_multiplier: 0.7
      momentum_weight_multiplier: 1.0
      volatility_weight_multiplier: 1.3
      volume_weight_multiplier: 1.2
    mixed:
      trend_weight_multiplier: 1.0
      momentum_weight_multiplier: 1.0
      volatility_weight_multiplier: 1.0
      volume_weight_multiplier: 1.0
