# Combined Strategy with Seasonality Configuration for Backtesting

# General backtest settings
general:
  symbols: ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META', 'NVDA', 'TSLA', 'JPM', 'BAC', 'XLF', 'XLK', 'XLE', 'XLU', 'XLB']
  timeframe: '1D'
  initial_capital: 100000
  position_size_pct: 0.1
  max_positions: 8
  backtest_start_date: '2023-01-01'
  backtest_end_date: '2024-03-01'
  log_level: 'INFO'

# Strategy-specific configurations
strategy_configs:
  MeanReversion:
    # Core parameters
    bb_period: 20
    bb_std: 1.9
    rsi_period: 14
    rsi_overbought: 65
    rsi_oversold: 35
    
    # Signal generation parameters
    require_reversal: true
    min_reversal_candles: 1
    
    # Risk management parameters
    stop_loss_atr_multiplier: 1.8
    take_profit_atr_multiplier: 3.0
    atr_period: 14
    
    # Filters
    volume_filter: true
    min_volume_percentile: 50
    
    # Weight in combined strategy
    weight: 0.6

  TrendFollowing:
    # Core parameters
    ema_short: 20
    ema_medium: 50
    ema_long: 200
    
    # Signal parameters
    min_trend_strength: 0.02
    
    # Risk management
    stop_loss_atr_multiplier: 2.0
    take_profit_atr_multiplier: 4.0
    atr_period: 14
    
    # Weight in combined strategy
    weight: 0.3

  Combined:
    # Strategy weights
    mean_reversion_weight: 0.6
    trend_following_weight: 0.3
    
    # Seasonality integration
    use_seasonality: true
    seasonality_weight: 0.3
    seasonal_boost: 0.2
    seasonal_penalty: 0.2
    
    # Signal threshold
    min_signal_score: 0.5
    max_signals_per_day: 5

# Symbol-specific configurations
symbol_configs:
  AAPL:
    weight_multiplier: 1.3
    stop_loss_pct: 0.02
    take_profit_pct: 0.04
  
  MSFT:
    weight_multiplier: 1.2
    stop_loss_pct: 0.02
    take_profit_pct: 0.04
  
  GOOGL:
    weight_multiplier: 1.1
    stop_loss_pct: 0.02
    take_profit_pct: 0.04
  
  AMZN:
    weight_multiplier: 1.1
    stop_loss_pct: 0.025
    take_profit_pct: 0.05
  
  META:
    weight_multiplier: 1.4
    stop_loss_pct: 0.03
    take_profit_pct: 0.06
  
  NVDA:
    weight_multiplier: 1.5
    stop_loss_pct: 0.03
    take_profit_pct: 0.06
  
  TSLA:
    weight_multiplier: 0.8
    stop_loss_pct: 0.04
    take_profit_pct: 0.08
  
  JPM:
    weight_multiplier: 1.2
    stop_loss_pct: 0.02
    take_profit_pct: 0.04
  
  BAC:
    weight_multiplier: 1.0
    stop_loss_pct: 0.02
    take_profit_pct: 0.04

# Seasonality file path
seasonality_file: 'output/seasonal_opportunities_converted.yaml'
