# Configuration for Combined Strategy with New Stock Set

# General settings
general:
  log_level: INFO
  initial_capital: 100000
  max_positions: 15
  max_portfolio_risk_pct: 0.02
  min_capital_per_trade: 1000
  symbols:
    - JPM    # Financial
    - JNJ    # Healthcare
    - PG     # Consumer Staples
    - DIS    # Entertainment
    - HD     # Retail
    - INTC   # Semiconductor
    - IBM    # Technology Services
    - CVX    # Energy
    - KO     # Beverage
    - MCD    # Restaurant
  timeframe: '1D'
  position_size_pct: 0.05  # Base position size (will be adjusted dynamically)
  backtest_start_date: '2023-01-01'
  backtest_end_date: '2024-04-30'
  min_signal_score: 0.55  # Lowered to allow more signals overall

# Strategy-specific configurations
strategy_configs:
  # Mean Reversion Strategy parameters
  MeanReversion:
    weight: 0.45
    bb_period: 20
    bb_std: 1.8
    rsi_period: 14
    rsi_lower: 38
    rsi_upper: 62
    require_reversal: true
    stop_loss_atr_multiplier: 1.6
    take_profit_atr_multiplier: 2.8
    atr_period: 14
    volume_filter: true
    volume_threshold: 1.3
    symbol_weights:
      JPM: 1.0
      JNJ: 1.0
      PG: 1.1
      DIS: 1.2
      HD: 1.1
      INTC: 1.3
      IBM: 1.0
      CVX: 1.2
      KO: 0.9
      MCD: 1.0

  # Trend Following Strategy parameters
  TrendFollowing:
    weight: 0.55
    fast_ma_period: 9
    slow_ma_period: 21
    signal_ma_period: 9
    adx_period: 14
    adx_threshold: 25
    macd_fast_period: 12
    macd_slow_period: 26
    macd_signal_period: 9
    rsi_period: 14
    rsi_lower: 40
    rsi_upper: 60
    atr_period: 14
    stop_loss_atr_multiplier: 1.5
    take_profit_atr_multiplier: 3.0
    volume_filter: true
    volume_threshold: 1.2
    symbol_weights:
      JPM: 1.1
      JNJ: 0.9
      PG: 1.0
      DIS: 1.2
      HD: 1.1
      INTC: 1.3
      IBM: 1.0
      CVX: 1.2
      KO: 0.9
      MCD: 1.0

  # Combined Strategy parameters
  Combined:
    mean_reversion_weight: 0.45
    trend_following_weight: 0.55
    trending_regime_weights:
      mean_reversion: 0.15
      trend_following: 0.85
    range_bound_regime_weights:
      mean_reversion: 0.75
      trend_following: 0.25
    mixed_regime_weights:
      mean_reversion: 0.55
      trend_following: 0.45
    regime_lookback: 20
    volatility_period: 10
    adx_threshold: 25
    min_signal_score: 0.55
    max_signals_per_day: 4
    position_size_pct: 0.05

# Risk management parameters
risk_management:
  max_portfolio_risk_pct: 0.02
  max_position_risk_pct: 0.005
  max_sector_exposure_pct: 0.20
  max_drawdown_exit_pct: 0.15
  trailing_stop_activation_pct: 0.05
  trailing_stop_distance_pct: 0.03
  profit_taking_levels:
    - level: 0.05
      size_reduction_pct: 0.25
    - level: 0.10
      size_reduction_pct: 0.50
  volatility_adjustment: true
  volatility_lookback: 20
  volatility_scaling_factor: 0.8

# Market regime configuration
market_regime:
  adx_threshold: 25
  volatility_period: 20
  regime_lookback: 10
  trending_weights:
    mean_reversion: 0.15
    trend_following: 0.85
  range_bound_weights:
    mean_reversion: 0.75
    trend_following: 0.25
  mixed_weights:
    mean_reversion: 0.55
    trend_following: 0.45

# Seasonality configuration
seasonality:
  enabled: true
  data_file: 'output/seasonal_opportunities_converted.yaml'
  min_score_threshold: 0.6
  weight_adjustment: true
  sector_influence: 0.3
  stock_specific_influence: 0.7
  top_n_selection: 10
