global:
  initial_capital: 100000
  max_positions: 10
  position_size_pct: 0.05  # 5% of capital per position
  max_risk_per_trade_pct: 0.01  # 1% max risk per trade
  max_correlated_positions: 3
  market_hours_only: true
  enable_logging: true
  log_level: INFO

stocks:
  AAPL:
    weight: 1.2
  MSFT:
    weight: 1.1
  GOOGL:
    weight: 1.0
  AMZN:
    weight: 1.0
  META:
    weight: 0.8  # Reduced weight for META based on poor performance
  SPY:
    weight: 1.3  # Increased weight for SPY as it's more stable

strategies:
  # Mean Reversion Strategy Configuration
  MeanReversion:
    base_weight: 0.35  # Further reduced weight for mean reversion
    
    # Bollinger Bands Parameters
    bb_period: 20
    bb_std: 1.9  # Slightly tighter bands than default
    
    # RSI Parameters
    rsi_period: 14
    rsi_oversold: 35  # Less extreme for more signals
    rsi_overbought: 65  # Less extreme for more signals
    
    # Signal Quality Parameters
    require_reversal: true  # Require price reversal for higher quality signals
    min_distance_to_band_pct: 0.01  # Increased minimum distance to BB for better quality signals
    
    # Risk Management
    atr_period: 14
    stop_loss_atr: 1.3  # Tighter stop loss
    take_profit_atr: 3.0  # Take profit at 3.0x ATR (2.3:1 reward-to-risk)
    
    # Symbol-specific weights (based on historical performance)
    symbol_weights:
      AAPL: 1.2
      MSFT: 1.1
      GOOGL: 1.0
      AMZN: 1.0
      META: 0.8
      SPY: 1.3

  # Trend Following Strategy Configuration
  TrendFollowing:
    base_weight: 0.65  # Increased weight for trend following
    
    # EMA Parameters
    fast_ema_period: 8  # Faster EMA for quicker signals
    slow_ema_period: 21
    
    # ADX Parameters
    adx_period: 14
    adx_threshold: 25  # Increased to filter out weaker signals
    
    # MACD Parameters
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    
    # Risk Management
    atr_period: 14
    stop_loss_atr: 1.2  # Tighter stop loss
    risk_reward_ratio: 2.8  # Increased reward-to-risk ratio
    
    # Symbol-specific weights (based on historical performance)
    symbol_weights:
      AAPL: 1.2
      MSFT: 1.1
      GOOGL: 1.0
      AMZN: 1.0
      META: 0.8
      SPY: 1.3
