strategies:
  MeanReversion:
    # Core parameters - optimized from previous testing
    bb_period: 20
    bb_std_dev: 1.9  # Using the optimized value from previous testing
    rsi_period: 14
    rsi_overbought: 65  # Less extreme for more signals
    rsi_oversold: 35    # Less extreme for more signals
    
    # Signal generation parameters
    require_reversal: true
    min_reversal_candles: 1
    
    # Risk management parameters
    stop_loss_atr: 1.8  # Optimized from previous testing
    take_profit_atr: 3.0  # Optimized from previous testing
    max_holding_days: 10  # Add maximum holding period
    
    # Position sizing parameters
    max_position_size: 0.08  # Slightly reduced for risk management
    
    # Strategy weight in multi-strategy system
    base_weight: 0.5  # Equal weight with trend following
    
    # Market regime detection parameters
    use_regime_filter: true
    min_regime_score: 0.3
    regime_filter_strength: 1.0
    
    # ML signal quality parameters
    use_ml_filter: true
    min_quality_score: 0.4
    ml_filter_strength: 1.0

  TrendFollowing:
    # Core parameters - adjusted for more sensitivity
    fast_ema_period: 8     # Reduced from 9 for quicker response
    slow_ema_period: 21
    adx_period: 14
    adx_threshold: 20      # Reduced from 25 to generate more signals
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    
    # Risk management parameters
    max_stop_distance_pct: 2.5  # Reduced for tighter risk control
    risk_reward_ratio: 2.0
    
    # Position sizing parameters
    max_position_size: 0.08  # Consistent with mean reversion
    
    # Strategy weight in multi-strategy system
    base_weight: 0.5  # Equal weight with mean reversion
    
    # Market regime detection parameters
    use_regime_filter: true
    min_regime_score: 0.3
    regime_filter_strength: 1.0

# Global settings
global:
  initial_capital: 100000
  max_open_positions: 6       # Increased from 5
  max_positions_per_symbol: 2
  max_correlated_positions: 3
  correlation_threshold: 0.7
  max_portfolio_risk_daily_pct: 1.5  # Reduced for more conservative risk
  rebalance_interval: 1d
  data_lookback_days: 30
  market_hours_start: '09:30'
  market_hours_end: '16:00'
  debug_mode: true

# Symbol-specific configurations - based on previous optimization
stocks:
  AAPL:
    weight_multiplier: 1.2
    max_position_size: 400    # Reduced for better risk management
    min_position_size: 10
    max_risk_per_trade_pct: 0.5
    
  MSFT:
    weight_multiplier: 1.1
    max_position_size: 400
    min_position_size: 10
    max_risk_per_trade_pct: 0.5
    
  GOOGL:
    weight_multiplier: 1.0
    max_position_size: 400
    min_position_size: 10
    max_risk_per_trade_pct: 0.5
    
  AMZN:
    weight_multiplier: 1.1
    max_position_size: 400
    min_position_size: 10
    max_risk_per_trade_pct: 0.5
    
  META:
    weight_multiplier: 1.3
    max_position_size: 400
    min_position_size: 10
    max_risk_per_trade_pct: 0.5
    
  SPY:
    weight_multiplier: 1.0
    max_position_size: 400
    min_position_size: 10
    max_risk_per_trade_pct: 0.4  # Lower risk for index ETF
