# Multi-Strategy Trading System Configuration
# ------------------------------------------

# Overall System Configuration
initial_capital: 100000.0         # Starting capital
max_open_positions: 10           # Maximum positions across all symbols
max_positions_per_symbol: 2      # Maximum positions per symbol
max_correlated_positions: 5      # Maximum correlated positions
max_sector_exposure_pct: 30.0    # Maximum exposure to any sector (%)
max_portfolio_risk_daily_pct: 2.0  # Maximum portfolio risk per day (%)
rebalance_interval: 1d           # Rebalance interval (d=days, h=hours)
data_lookback_days: 30           # Days of historical data to maintain
market_hours_start: '09:30'      # Market open time (EST)
market_hours_end: '16:00'        # Market close time (EST)
debug_mode: true                 # Enable debug mode for more verbose logging

# Data Source Configuration
data_source: YAHOO             # Data source (YAHOO, ALPACA, IB)
api_key: null                  # API key (if required)
api_secret: null               # API secret (if required)

# Strategy Weights (initial weights, will adapt based on performance)
strategy_weights:
  MeanReversion: 0.25          # Mean reversion strategy weight
  TrendFollowing: 0.25         # Trend following strategy weight
  VolatilityBreakout: 0.25     # Volatility breakout strategy weight
  GapTrading: 0.25             # Gap trading strategy weight

# Trading Configuration
enable_auto_trading: false     # Enable automated trading
backtesting_mode: true         # Enable backtesting mode

# Signal Quality Filters Configuration
signal_quality_filters:
  min_score_threshold: 0.6       # Minimum signal score to consider
  max_correlation_threshold: 0.7 # Maximum correlation between signals
  min_volume_percentile: 50      # Minimum volume percentile
  min_price: 5.0                 # Minimum price for a stock
  max_spread_percent: 1.0        # Maximum bid-ask spread percentage
  min_volatility_percentile: 20  # Minimum volatility percentile
  max_volatility_percentile: 90  # Maximum volatility percentile
  min_regime_weight: 0.3         # Minimum regime weight for a strategy
  max_signals_per_regime: 5      # Maximum signals per market regime
  max_sector_exposure: 0.3       # Maximum sector exposure (as fraction)
  max_signals_per_day: 10        # Maximum signals per day

# Adaptive Position Sizing Configuration
position_sizing_config:
  base_risk_per_trade: 0.01      # Base risk per trade (as fraction of portfolio)
  max_position_size: 0.1         # Maximum position size (as fraction of portfolio)
  min_position_size: 0.005       # Minimum position size (as fraction of portfolio)
  volatility_adjustment: true     # Enable volatility-based position sizing
  signal_strength_adjustment: true # Enable signal strength-based position sizing

# ML-Based Strategy Selection Configuration
ml_strategy_selector:
  ml_lookback_window: 30         # Lookback window for ML training (days)
  ml_min_training_samples: 100   # Minimum training samples required
  ml_retraining_frequency: 7     # Retraining frequency (days)
  ml_feature_columns:            # Features used for ML models
    - vix
    - market_adx
    - trending_strength
    - range_bound_strength
    - volatility_strength
    - regime_change_probability

# Stocks Configuration
stocks:
  - symbol: AAPL
    max_position_size: 500
    min_position_size: 10
    max_risk_per_trade_pct: 0.5
    min_volume: 10000
    beta: 1.2
    sector: Technology
    industry: Consumer Electronics
    mean_reversion_params:
      bb_period: 10
      bb_std_dev: 1.0
      rsi_period: 7
      rsi_overbought: 60
      rsi_oversold: 40
      min_reversal_candles: 1
    trend_following_params:
      adx_threshold: 15
      adx_period: 7
      ema_short: 5
      ema_long: 10
    volatility_breakout_params:
      min_squeeze_periods: 3
      bollinger_period: 10
      keltner_period: 10
    gap_trading_params:
      min_gap_pct: 0.5
  
  - symbol: MSFT
    max_position_size: 500
    min_position_size: 10
    max_risk_per_trade_pct: 0.5
    min_volume: 10000
    beta: 1.1
    sector: Technology
    industry: Software
    mean_reversion_params:
      bb_period: 10
      bb_std_dev: 1.0
      rsi_period: 7
      rsi_overbought: 60
      rsi_oversold: 40
      min_reversal_candles: 1
    trend_following_params:
      adx_threshold: 15
      adx_period: 7
      ema_short: 5
      ema_long: 10
    volatility_breakout_params:
      min_squeeze_periods: 3
      bollinger_period: 10
      keltner_period: 10
    gap_trading_params:
      min_gap_pct: 0.5
  
  - symbol: GOOGL
    max_position_size: 500
    min_position_size: 10
    max_risk_per_trade_pct: 0.5
    min_volume: 10000
    beta: 1.3
    sector: Technology
    industry: Internet Services
    mean_reversion_params:
      bb_period: 10
      bb_std_dev: 1.0
      rsi_period: 7
      rsi_overbought: 60
      rsi_oversold: 40
      min_reversal_candles: 1
    trend_following_params:
      adx_threshold: 15
      adx_period: 7
      ema_short: 5
      ema_long: 10
    volatility_breakout_params:
      min_squeeze_periods: 3
      bollinger_period: 10
      keltner_period: 10
    gap_trading_params:
      min_gap_pct: 0.5
  
  - symbol: AMZN
    max_position_size: 200
    min_position_size: 5
    max_risk_per_trade_pct: 0.5
    min_volume: 10000
    beta: 1.4
    sector: Consumer Discretionary
    industry: E-Commerce
    mean_reversion_params:
      bb_period: 10
      bb_std_dev: 1.0
      rsi_period: 7
      rsi_overbought: 60
      rsi_oversold: 40
      min_reversal_candles: 1
    trend_following_params:
      adx_threshold: 15
      adx_period: 7
      ema_short: 5
      ema_long: 10
    volatility_breakout_params:
      min_squeeze_periods: 3
      bollinger_period: 10
      keltner_period: 10
    gap_trading_params:
      min_gap_pct: 0.5
  
  - symbol: META
    max_position_size: 300
    min_position_size: 5
    max_risk_per_trade_pct: 0.5
    min_volume: 10000
    beta: 1.2
    sector: Technology
    industry: Social Media
    mean_reversion_params:
      bb_period: 10
      bb_std_dev: 1.0
      rsi_period: 7
      rsi_overbought: 60
      rsi_oversold: 40
      min_reversal_candles: 1
    trend_following_params:
      adx_threshold: 15
      adx_period: 7
      ema_short: 5
      ema_long: 10
    volatility_breakout_params:
      min_squeeze_periods: 3
      bollinger_period: 10
      keltner_period: 10
    gap_trading_params:
      min_gap_pct: 0.5
  
  - symbol: NVDA
    max_position_size: 300
    min_position_size: 5
    max_risk_per_trade_pct: 0.5
    min_volume: 10000
    beta: 1.5
    sector: Technology
    industry: Semiconductors
    mean_reversion_params:
      bb_period: 10
      bb_std_dev: 1.0
      rsi_period: 7
      rsi_overbought: 60
      rsi_oversold: 40
      min_reversal_candles: 1
    trend_following_params:
      adx_threshold: 15
      adx_period: 7
      ema_short: 5
      ema_long: 10
    volatility_breakout_params:
      min_squeeze_periods: 3
      bollinger_period: 10
      keltner_period: 10
    gap_trading_params:
      min_gap_pct: 0.5
  
  - symbol: AMD
    max_position_size: 400
    min_position_size: 10
    max_risk_per_trade_pct: 0.5
    min_volume: 10000
    beta: 1.4
    sector: Technology
    industry: Semiconductors
    mean_reversion_params:
      bb_std_dev: 1.5
      rsi_overbought: 65
      rsi_oversold: 35
    trend_following_params:
      adx_threshold: 20
    volatility_breakout_params:
      min_squeeze_periods: 6
    gap_trading_params:
      min_gap_pct: 1.0
  
  - symbol: TSLA
    max_position_size: 100
    min_position_size: 5
    max_risk_per_trade_pct: 0.5
    min_volume: 10000
    beta: 1.8
    sector: Consumer Cyclical
    industry: Auto Manufacturers
    mean_reversion_params:
      bb_std_dev: 1.5
      rsi_overbought: 65
      rsi_oversold: 35
    trend_following_params:
      adx_threshold: 20
    volatility_breakout_params:
      min_squeeze_periods: 6
    gap_trading_params:
      min_gap_pct: 1.0
  
  - symbol: JPM
    max_position_size: 400
    min_position_size: 10
    max_risk_per_trade_pct: 0.4
    min_volume: 5000
    beta: 1.1
    sector: Financial Services
    industry: Banks
    mean_reversion_params:
      bb_std_dev: 1.5
      rsi_overbought: 65
      rsi_oversold: 35
    trend_following_params:
      adx_threshold: 20
    volatility_breakout_params:
      min_squeeze_periods: 6
    gap_trading_params:
      min_gap_pct: 1.0
  
  - symbol: DIS
    max_position_size: 400
    min_position_size: 10
    max_risk_per_trade_pct: 0.4
    min_volume: 5000
    beta: 1.0
    sector: Communication Services
    industry: Entertainment
    mean_reversion_params:
      bb_std_dev: 1.5
      rsi_overbought: 65
      rsi_oversold: 35
    trend_following_params:
      adx_threshold: 20
    volatility_breakout_params:
      min_squeeze_periods: 6
    gap_trading_params:
      min_gap_pct: 1.0
  
  - symbol: SPY
    max_position_size: 500
    min_position_size: 10
    max_risk_per_trade_pct: 0.3
    min_volume: 5000
    beta: 1.0
    sector: Index
    industry: S&P 500
    mean_reversion_params:
      bb_std_dev: 1.5
      rsi_overbought: 65
      rsi_oversold: 35
    trend_following_params:
      adx_threshold: 20
    volatility_breakout_params:
      min_squeeze_periods: 6
    gap_trading_params:
      min_gap_pct: 1.0
  
  - symbol: V
    max_position_size: 400
    min_position_size: 10
    max_risk_per_trade_pct: 0.3
    min_volume: 5000
    beta: 0.9
    sector: Financial Services
    industry: Credit Services
    mean_reversion_params:
      bb_std_dev: 1.5
      rsi_overbought: 65
      rsi_oversold: 35
    trend_following_params:
      adx_threshold: 20
    volatility_breakout_params:
      min_squeeze_periods: 6
    gap_trading_params:
      min_gap_pct: 1.0