global:
  initial_capital: 100000
  max_positions: 10
  position_size_pct: 0.05  # 5% of capital per position
  max_risk_per_trade_pct: 0.01  # 1% max risk per trade
  max_correlated_positions: 3
  market_hours_only: true
  enable_logging: true
  log_level: INFO

stocks:
  AAPL:
    weight: 1.2
  MSFT:
    weight: 1.1
  GOOGL:
    weight: 1.0
  AMZN:
    weight: 1.0
  META:
    weight: 0.8  # Reduced weight for META based on poor performance
  SPY:
    weight: 1.3  # Increased weight for SPY as it's more stable

strategies:
  # Mean Reversion Strategy Configuration
  MeanReversion:
    base_weight: 0.45  # Increased weight for mean reversion
    
    # Bollinger Bands Parameters
    bb_period: 20
    bb_std: 2.0  # Standard 2.0 deviation bands
    
    # RSI Parameters
    rsi_period: 14
    rsi_oversold: 30  # More extreme for higher quality signals
    rsi_overbought: 70  # More extreme for higher quality signals
    
    # Signal Quality Parameters
    require_reversal: true  # Require price reversal for higher quality signals
    min_distance_to_band_pct: 0.015  # Increased minimum distance to BB for better quality signals
    
    # Risk Management
    atr_period: 14
    stop_loss_atr: 1.5  # Slightly wider stop loss
    take_profit_atr: 3.0  # Take profit at 3.0x ATR (2.0:1 reward-to-risk)
    
    # Symbol-specific weights (based on historical performance)
    symbol_weights:
      AAPL: 1.2
      MSFT: 1.1
      GOOGL: 1.0
      AMZN: 1.0
      META: 0.8
      SPY: 1.3

  # Trend Following Strategy Configuration
  TrendFollowing:
    base_weight: 0.55  # Decreased weight for trend following
    
    # EMA Parameters
    fast_ema_period: 9  # Adjusted for better crossover signals
    slow_ema_period: 25  # Increased to better identify longer trends
    
    # ADX Parameters
    adx_period: 14
    adx_threshold: 20  # Lowered to generate more signals
    
    # MACD Parameters
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    
    # Volume Confirmation
    volume_confirmation: true
    volume_threshold: 1.2  # Volume should be 1.2x the average
    
    # Risk Management
    atr_period: 14
    stop_loss_atr: 1.5  # Wider stop loss to avoid premature exits
    risk_reward_ratio: 2.5  # Slightly reduced but still good reward-to-risk ratio
    
    # Symbol-specific weights (based on historical performance)
    symbol_weights:
      AAPL: 1.2
      MSFT: 1.1
      GOOGL: 1.0
      AMZN: 1.0
      META: 0.7  # Further reduced weight for META
      SPY: 1.4  # Further increased weight for SPY
