global:
  correlation_threshold: 0.7
  default_position_size: 0.05
  max_correlated_positions: 3
  max_open_positions: 5
  max_portfolio_risk: 0.02
  max_positions_per_symbol: 2
initial_capital: 100000
position_sizing_config:
  base_risk_per_trade: 0.01
  max_position_size: 0.1
  min_position_size: 0.005
stocks:
  AAPL:
    position_size: 0.08
    strategies:
      MeanReversion:
        weight_multiplier: 1.3
  AMZN:
    position_size: 0.07
    strategies:
      MeanReversion:
        weight_multiplier: 1.1
  GOOGL:
    position_size: 0.07
    strategies:
      MeanReversion:
        weight_multiplier: 1.1
  META:
    position_size: 0.07
    strategies:
      MeanReversion:
        weight_multiplier: 1.4
  MSFT:
    position_size: 0.08
    strategies:
      MeanReversion:
        weight_multiplier: 1.2
strategies:
  GapTrading:
    base_weight: 0.2
  MeanReversion:
    base_weight: 0.35
    bb_period: 20
    bb_std_dev: 1.9
    max_position_size: 0.1
    min_reversal_candles: 1
    require_reversal: true
    rsi_overbought: 65
    rsi_oversold: 35
    rsi_period: 14
    stop_loss_atr: 1.8
    take_profit_atr: 3.0
  TrendFollowing:
    base_weight: 0.25
  VolatilityBreakout:
    base_weight: 0.2
symbols:
- symbol: AAPL
  weight: 1.0
- symbol: MSFT
  weight: 1.0
- symbol: AMZN
  weight: 1.0
- symbol: GOOGL
  weight: 1.0
- symbol: META
  weight: 1.0
