# Configuration for Enhanced Multi-Factor Strategy

# General settings
general:
  log_level: INFO
  initial_capital: 100000
  max_positions: 15
  max_portfolio_risk_pct: 0.02
  min_capital_per_trade: 1000
  symbols:
    - SPY
    - QQQ
    - AAPL
    - MSFT
    - AMZN
    - GOOGL
    - TSLA
    - NVDA
    - AMD
    - META
    - INTC
    - JPM
    - V
    - DIS
    - HD
  timeframe: '1D'
  position_size_pct: 0.05  # Base position size (will be adjusted dynamically)
  backtest_start_date: '2023-01-01'
  backtest_end_date: '2024-04-30'
  min_signal_score: 0.55  # Minimum score to consider a signal valid
  max_signals_per_day: 8   # Maximum number of signals to generate per day

# Strategy weights
strategy_weights:
  mean_reversion: 0.45  # Weight for mean reversion strategy
  trend_following: 0.45  # Weight for trend following strategy
  # Note: remaining 10% is implicitly allocated to seasonality

# Enhanced stock selection with multi-factor approach
stock_selection:
  use_multi_factor: true  # Enable multi-factor stock selection
  technical_weight: 0.6   # Weight for technical indicators in combined score
  seasonality_weight: 0.4  # Weight for seasonality in combined score
  
  # Weights for different technical components
  momentum_weight: 0.3    # Weight for momentum indicators (RSI, MACD)
  trend_weight: 0.3       # Weight for trend indicators (Moving Averages, ADX)
  volatility_weight: 0.2  # Weight for volatility metrics (ATR, BB width)
  volume_weight: 0.2      # Weight for volume indicators (OBV, Volume)
  
  alignment_boost: 0.1    # Boost for signals that align with multiple factors
  top_n_stocks: 5         # Number of top stocks to select from universe

# Seasonality configuration
seasonality:
  enabled: true
  data_file: 'data/seasonality.yaml'  # Path to seasonality data file
  min_score_threshold: 0.6  # Minimum seasonality score to keep a signal
  weight_adjustment: true   # Adjust signal weights based on seasonality
  sector_influence: 0.3     # Weight for sector seasonality
  stock_specific_influence: 0.7  # Weight for stock-specific seasonality
  top_n_selection: 5        # Number of top seasonal stocks to select

# Strategy-specific configurations
strategy_configs:
  # Mean Reversion Strategy parameters
  MeanReversion:
    weight: 0.45
    bb_period: 20
    bb_std: 1.8
    rsi_period: 14
    rsi_lower: 38
    rsi_upper: 62
    require_reversal: true
    stop_loss_atr_multiplier: 1.6
    take_profit_atr_multiplier: 2.8
    atr_period: 14
    volume_filter: true
    volume_threshold: 1.3
    symbol_weights:
      SPY: 1.0
      QQQ: 1.0
      AAPL: 1.2
      MSFT: 1.1
      AMZN: 1.2
      GOOGL: 0.9
      TSLA: 1.3
      NVDA: 1.2
      AMD: 1.3
      META: 1.1
      INTC: 0.9
      JPM: 0.8
      V: 1.0
      DIS: 0.9
      HD: 0.8

  # Trend Following Strategy parameters
  TrendFollowing:
    weight: 0.45
    fast_ma_period: 10
    slow_ma_period: 30
    signal_ma_period: 9
    atr_period: 14
    stop_loss_atr_multiplier: 2.0
    take_profit_atr_multiplier: 3.5
    volume_filter: true
    volume_threshold: 1.2
    trend_strength_threshold: 25
    symbol_weights:
      SPY: 1.0
      QQQ: 1.0
      AAPL: 1.1
      MSFT: 1.2
      AMZN: 1.1
      GOOGL: 1.0
      TSLA: 1.4
      NVDA: 1.3
      AMD: 1.2
      META: 1.2
      INTC: 0.8
      JPM: 0.9
      V: 1.1
      DIS: 0.8
      HD: 0.9

  # Combined Strategy parameters
  Combined:
    mean_reversion_weight: 0.45
    trend_following_weight: 0.45
    seasonality_weight: 0.1
    use_seasonality: true
    seasonal_boost: 0.2   # Boost for signals that align with seasonality
    seasonal_penalty: 0.2  # Penalty for signals that contradict seasonality
    adx_threshold: 22     # Threshold for ADX to determine trending market
    volatility_period: 20  # Period for calculating volatility
    regime_lookback: 10   # Lookback period for market regime detection
    min_signal_score: 0.6  # Minimum score required for a valid signal

# Symbol-specific configurations
symbol_configs:
  AAPL:
    weight_multiplier: 1.2
    risk_multiplier: 1.0
  MSFT:
    weight_multiplier: 1.1
    risk_multiplier: 0.9
  AMZN:
    weight_multiplier: 1.2
    risk_multiplier: 1.1
  GOOGL:
    weight_multiplier: 1.0
    risk_multiplier: 0.9
  TSLA:
    weight_multiplier: 1.3
    risk_multiplier: 1.2
  NVDA:
    weight_multiplier: 1.3
    risk_multiplier: 1.1
  AMD:
    weight_multiplier: 1.2
    risk_multiplier: 1.1
  META:
    weight_multiplier: 1.1
    risk_multiplier: 1.0
  INTC:
    weight_multiplier: 0.8
    risk_multiplier: 0.9
  JPM:
    weight_multiplier: 0.9
    risk_multiplier: 0.8
  V:
    weight_multiplier: 1.0
    risk_multiplier: 0.9
  DIS:
    weight_multiplier: 0.9
    risk_multiplier: 1.0
  HD:
    weight_multiplier: 0.9
    risk_multiplier: 0.9
