# Configuration for Seasonality Integration Testing

# General settings
general:
  log_level: INFO
  initial_capital: 100000
  max_positions: 15
  max_portfolio_risk_pct: 0.02
  min_capital_per_trade: 1000
  symbols:
    - SPY
    - QQQ
    - AAPL
    - MSFT
    - AMZN
    - GOOGL
    - TSLA
    - NVDA
    - AMD
  timeframe: '1D'
  position_size_pct: 0.05  # Base position size (will be adjusted dynamically)
  backtest_start_date: '2023-01-01'
  backtest_end_date: '2023-12-31'
  min_signal_score: 0.5  # Lowered to allow more signals for testing seasonality

# Strategy-specific configurations
strategy_configs:
  # Mean Reversion Strategy parameters
  MeanReversion:
    weight: 0.5  # Balanced with trend following
    bb_period: 20
    bb_std: 1.9  # Using optimized value from previous testing
    rsi_period: 14
    rsi_lower: 35  # Using optimized value from previous testing
    rsi_upper: 65  # Using optimized value from previous testing
    require_reversal: true
    stop_loss_atr_multiplier: 1.8  # Using optimized value from previous testing
    take_profit_atr_multiplier: 3.0  # Using optimized value from previous testing
    atr_period: 14
    volume_filter: true
    volume_threshold: 1.3
    symbol_weights:
      SPY: 1.0
      QQQ: 1.0
      AAPL: 1.2
      MSFT: 1.1
      AMZN: 1.2
      GOOGL: 0.9
      TSLA: 1.3
      NVDA: 1.2
      AMD: 1.3

  # Trend Following Strategy parameters
  TrendFollowing:
    weight: 0.5  # Balanced with mean reversion
    fast_ma_period: 9
    slow_ma_period: 21
    signal_ma_period: 9
    adx_period: 14
    adx_threshold: 25
    macd_fast_period: 12
    macd_slow_period: 26
    macd_signal_period: 9
    rsi_period: 14
    rsi_lower: 40
    rsi_upper: 60
    atr_period: 14
    stop_loss_atr_multiplier: 1.5
    take_profit_atr_multiplier: 3.0
    volume_filter: true
    volume_threshold: 1.2
    symbol_weights:
      SPY: 1.1
      QQQ: 1.2
      AAPL: 1.0
      MSFT: 1.1
      AMZN: 1.0
      GOOGL: 1.0
      TSLA: 1.3
      NVDA: 1.3
      AMD: 1.2

  # Combined Strategy parameters
  Combined:
    mean_reversion_weight: 0.5  # Balanced weight
    trend_following_weight: 0.5  # Balanced weight
    
    # Enhanced seasonality settings
    use_seasonality: true
    seasonality_weight: 0.4  # Increased from default to emphasize seasonality
    seasonal_boost: 0.3  # Increased from default to make seasonality impact more visible
    seasonal_penalty: 0.3  # Increased from default to make seasonality impact more visible
    
    # Market regime weights
    trending_regime_weights:
      mean_reversion: 0.2
      trend_following: 0.8
    range_bound_regime_weights:
      mean_reversion: 0.8
      trend_following: 0.2
    mixed_regime_weights:
      mean_reversion: 0.5
      trend_following: 0.5
    
    # Regime detection parameters
    regime_lookback: 20
    volatility_period: 10
    adx_threshold: 25
    
    # Signal filtering parameters
    min_signal_score: 0.5  # Lowered to allow more signals for testing
    max_signals_per_day: 5  # Increased to allow more signals for testing
    position_size_pct: 0.05
    max_risk_per_trade_pct: 0.01
    max_correlation_threshold: 0.7
    max_sector_exposure_pct: 0.3

# Symbol-specific configurations
symbol_configs:
  SPY:
    weight_multiplier: 1.2
    risk_multiplier: 0.9
  QQQ:
    weight_multiplier: 1.3
    risk_multiplier: 1.0
  AAPL:
    weight_multiplier: 1.1
    risk_multiplier: 1.0
  MSFT:
    weight_multiplier: 1.1
    risk_multiplier: 1.0
  AMZN:
    weight_multiplier: 1.0
    risk_multiplier: 1.0
  GOOGL:
    weight_multiplier: 1.0
    risk_multiplier: 1.0
  TSLA:
    weight_multiplier: 1.2
    risk_multiplier: 1.1
  NVDA:
    weight_multiplier: 1.1
    risk_multiplier: 1.0
  AMD:
    weight_multiplier: 1.0
    risk_multiplier: 0.9

# Seasonality configuration
seasonality_file: 'output/seasonal_opportunities_converted.yaml'
