# Configuration for Ultra Aggressive Strategy for March 2023 Backtest

# General settings
general:
  log_level: INFO
  initial_capital: 100000
  max_positions: 20  # Increased to allow more positions
  max_portfolio_risk_pct: 0.03  # Increased risk
  min_capital_per_trade: 500  # Smaller minimum position size
  symbols:
    # Top performing symbols based on March 2023 backtest analysis
    - META   # Top performer in backtest
    - JPM    # Strong performer in backtest
    - MRK    # Strong performer in backtest
    - VLO    # Good performer in backtest
    - CVX    # Good performer in backtest
    - TSLA   # Good performer in backtest
    - V      # Positive performer in backtest
    # Additional symbols for diversification
    - AAPL
    - MSFT
    - AMZN
    - GOOGL
    - NEE
    - LIN
    - NVDA
    - DE
    - EOG
    - PSX
    - XLU
    - WMT
    - PG
  timeframe: '1D'
  position_size_pct: 0.05  # Base position size (will be adjusted dynamically)
  backtest_start_date: '2023-03-01'
  backtest_end_date: '2023-03-31'
  min_signal_score: 0.1  # Extremely low to allow almost any signal
  max_signals_per_day: 20  # Increased to allow many signals per day

# Strategy-specific configurations
strategy_configs:
  # Mean Reversion Strategy parameters - Ultra Aggressive
  MeanReversion:
    weight: 0.6  # Higher weight for mean reversion
    bb_period: 5  # Very short period
    bb_std: 0.5   # Very tight bands
    rsi_period: 3  # Very short period
    rsi_lower: 45  # Higher threshold for more buy signals
    rsi_upper: 55  # Lower threshold for more sell signals
    require_reversal: false  # Don't require reversal
    stop_loss_atr_multiplier: 3.0  # Wider stop loss
    take_profit_atr_multiplier: 2.0  # Shorter take profit
    atr_period: 7  # Shorter ATR period
    volume_filter: false  # No volume filtering
    min_volume_percentile: 0  # No volume requirement
    min_atr_percentile: 0  # No ATR requirement
    min_price: 1.0  # Allow lower priced stocks
    max_price: 5000.0  # Allow higher priced stocks
    max_spread_pct: 2.0  # Allow wider spreads
    signal_expiry_bars: 5  # Longer signal validity
    entry_limit_pct: 1.0  # Wider entry limit
    exit_limit_pct: 1.0  # Wider exit limit
    symbol_weights:  # Adjusted weights based on backtest performance
      META: 2.5  # Top performer
      JPM: 2.0
      MRK: 2.0
      VLO: 1.8
      CVX: 1.8
      TSLA: 1.5
      V: 1.5
      AAPL: 1.0
      MSFT: 1.0
      AMZN: 1.0
      GOOGL: 1.0
      NEE: 1.0
      LIN: 1.0
      NVDA: 1.0
      DE: 1.0
      EOG: 1.0
      PSX: 1.0
      XLU: 1.0
      WMT: 1.0
      PG: 1.0

  # Trend Following Strategy parameters - Also more aggressive
  TrendFollowing:
    weight: 0.4  # Lower weight for trend following
    ema_short: 5  # Very short EMA
    ema_medium: 10  # Short medium EMA
    ema_long: 20  # Short long EMA
    macd_fast: 6  # Faster MACD
    macd_slow: 13  # Faster slow line
    macd_signal: 4  # Faster signal line
    adx_period: 7  # Shorter ADX period
    adx_threshold: 5  # Very low threshold
    stop_loss_atr_multiplier: 3.0  # Wider stop loss
    take_profit_atr_multiplier: 2.0  # Shorter take profit
    atr_period: 7  # Shorter ATR period
    volume_filter: false  # No volume filtering
    min_volume_percentile: 0  # No volume requirement
    min_atr_percentile: 0  # No ATR requirement
    min_price: 1.0  # Allow lower priced stocks
    max_price: 5000.0  # Allow higher priced stocks
    max_spread_pct: 2.0  # Allow wider spreads
    signal_expiry_bars: 5  # Longer signal validity
    entry_limit_pct: 1.0  # Wider entry limit
    exit_limit_pct: 1.0  # Wider exit limit
    symbol_weights:  # Adjusted weights based on backtest performance
      META: 2.5  # Top performer
      JPM: 2.0
      MRK: 2.0
      VLO: 1.8
      CVX: 1.8
      TSLA: 1.5
      V: 1.5
      AAPL: 1.0
      MSFT: 1.0
      AMZN: 1.0
      GOOGL: 1.0
      NEE: 1.0
      LIN: 1.0
      NVDA: 1.0
      DE: 1.0
      EOG: 1.0
      PSX: 1.0
      XLU: 1.0
      WMT: 1.0
      PG: 1.0

  # Combined Strategy parameters
  Combined:
    mean_reversion_weight: 0.6  # Higher weight for mean reversion
    trend_following_weight: 0.4  # Lower weight for trend following
    adx_threshold: 5  # Very low threshold
    volatility_period: 10  # Shorter volatility period
    regime_lookback: 5  # Shorter lookback
    min_signal_score: 0.1  # Extremely low to allow almost any signal
    use_multi_factor: false  # Disable multi-factor to simplify

# Seasonality parameters
seasonality:
  enabled: true
  data_file: 'output/seasonal_opportunities_converted.yaml'
  min_score_threshold: 0.3  # Lower threshold
  weight_adjustment: true
  sector_influence: 0.3
  stock_specific_influence: 0.7
  top_n_selection: 20  # Increased
  boost_factor: 0.8  # Higher boost
  penalty_factor: 0.1  # Lower penalty

# Risk management
risk_management:
  max_drawdown_pct: 30  # Higher max drawdown
  max_daily_loss_pct: 5  # Higher daily loss limit
  max_position_size_pct: 20  # Higher position size
  trailing_stop_enabled: false  # Disable trailing stops
  trailing_stop_activation_pct: 1.0
  trailing_stop_distance_pct: 0.5
  profit_taking_enabled: false  # Disable profit taking
  profit_taking_threshold_pct: 3.0
  profit_taking_size_pct: 50
