# MeanReversion Strategy Configuration for 2024 Backtests
# Based on the optimized parameters from previous testing

# Initial capital
initial_capital: 100000

# Position Sizing Configuration
position_sizing_config:
  base_risk_per_trade: 0.01      # Base risk per trade (as fraction of portfolio)
  max_position_size: 0.1         # Maximum position size (as fraction of portfolio)
  min_position_size: 0.005       # Minimum position size (as fraction of portfolio)
  volatility_adjustment: true    # Enable volatility-based position sizing
  signal_strength_adjustment: true # Enable signal strength-based position sizing

# MeanReversion Strategy Parameters
mean_reversion_params:
  bb_period: 20                  # Bollinger Bands period
  bb_std_dev: 1.9                # Bollinger Bands standard deviation
  rsi_period: 14                 # RSI period
  rsi_overbought: 65             # RSI overbought threshold (less extreme for more signals)
  rsi_oversold: 35               # RSI oversold threshold (less extreme for more signals)
  require_reversal: true         # Require price reversal for higher quality signals
  min_reversal_candles: 1        # Minimum candles for reversal pattern
  stop_loss_atr: 1.8             # Stop loss at 1.8x ATR
  take_profit_atr: 3.0           # Take profit at 3.0x ATR
  atr_period: 14                 # ATR period for volatility measurement

# Global settings
max_open_positions: 10           # Maximum number of open positions
max_positions_per_symbol: 1      # Maximum positions per symbol
risk_per_trade: 0.01             # Risk per trade (1% of portfolio)
max_risk_per_trade_pct: 0.02     # Maximum risk per trade (2% of portfolio)

# Stocks to test
stocks:
  - symbol: AAPL
    max_position_size: 500
    min_position_size: 10
    max_risk_per_trade_pct: 0.02
    min_volume: 10000
    sector: Technology
    mean_reversion_params:
      weight_multiplier: 1.3     # Symbol-specific weight multiplier
  
  - symbol: MSFT
    max_position_size: 500
    min_position_size: 10
    max_risk_per_trade_pct: 0.02
    min_volume: 10000
    sector: Technology
    mean_reversion_params:
      weight_multiplier: 1.2
  
  - symbol: GOOGL
    max_position_size: 500
    min_position_size: 10
    max_risk_per_trade_pct: 0.02
    min_volume: 10000
    sector: Technology
    mean_reversion_params:
      weight_multiplier: 1.1
  
  - symbol: AMZN
    max_position_size: 500
    min_position_size: 10
    max_risk_per_trade_pct: 0.02
    min_volume: 10000
    sector: Consumer Discretionary
    mean_reversion_params:
      weight_multiplier: 1.2
  
  - symbol: META
    max_position_size: 500
    min_position_size: 10
    max_risk_per_trade_pct: 0.02
    min_volume: 10000
    sector: Communication Services
    mean_reversion_params:
      weight_multiplier: 1.1
  
  - symbol: NVDA
    max_position_size: 500
    min_position_size: 10
    max_risk_per_trade_pct: 0.02
    min_volume: 10000
    sector: Technology
    mean_reversion_params:
      weight_multiplier: 1.3
  
  - symbol: AMD
    max_position_size: 500
    min_position_size: 10
    max_risk_per_trade_pct: 0.02
    min_volume: 10000
    sector: Technology
    mean_reversion_params:
      weight_multiplier: 1.0
  
  - symbol: TSLA
    max_position_size: 500
    min_position_size: 10
    max_risk_per_trade_pct: 0.02
    min_volume: 10000
    sector: Consumer Discretionary
    mean_reversion_params:
      weight_multiplier: 1.1
  
  - symbol: JPM
    max_position_size: 500
    min_position_size: 10
    max_risk_per_trade_pct: 0.02
    min_volume: 10000
    sector: Financials
    mean_reversion_params:
      weight_multiplier: 0.9
  
  - symbol: DIS
    max_position_size: 500
    min_position_size: 10
    max_risk_per_trade_pct: 0.02
    min_volume: 10000
    sector: Communication Services
    mean_reversion_params:
      weight_multiplier: 0.9

# Crypto to test
cryptos:
  - symbol: BTC/USD
    max_position_size: 5
    min_position_size: 0.01
    max_risk_per_trade_pct: 0.02
    min_volume: 1000
    mean_reversion_params:
      weight_multiplier: 1.2
      bb_period: 20
      bb_std_dev: 2.0
      rsi_period: 14
      rsi_overbought: 70
      rsi_oversold: 30
      stop_loss_atr: 2.0
      take_profit_atr: 3.5
  
  - symbol: ETH/USD
    max_position_size: 10
    min_position_size: 0.05
    max_risk_per_trade_pct: 0.02
    min_volume: 1000
    mean_reversion_params:
      weight_multiplier: 1.1
      bb_period: 20
      bb_std_dev: 2.0
      rsi_period: 14
      rsi_overbought: 70
      rsi_oversold: 30
      stop_loss_atr: 2.0
      take_profit_atr: 3.5
