# Enhanced Alpaca Trading System Configuration
# ------------------------------------------

# Overall System Configuration
initial_capital: 100000.0         # Starting capital
max_open_positions: 20           # Maximum positions across all symbols
max_positions_per_symbol: 3      # Maximum positions per symbol
max_correlated_positions: 8      # Maximum correlated positions
max_sector_exposure_pct: 40.0    # Maximum exposure to any sector (%)
max_portfolio_risk_daily_pct: 3.0  # Maximum portfolio risk per day (%)
rebalance_interval: 1d           # Rebalance interval (d=days, h=hours)
data_lookback_days: 60           # Days of historical data to maintain
market_hours_start: '09:30'      # Market open time (EST)
market_hours_end: '16:00'        # Market close time (EST)
debug_mode: true                 # Enable debug mode for more verbose logging

# Data Source Configuration
data_source: ALPACA             # Data source (YAHOO, ALPACA, IB)
api_key: null                   # API key (loaded from credentials file)
api_secret: null                # API secret (loaded from credentials file)

# Strategy Weights (optimized weights based on performance)
strategy_weights:
  MeanReversion: 0.40          # Mean reversion strategy weight
  TrendFollowing: 0.30         # Trend following strategy weight
  VolatilityBreakout: 0.20     # Volatility breakout strategy weight
  GapTrading: 0.10             # Gap trading strategy weight

# Trading Configuration
enable_auto_trading: false     # Enable automated trading
backtesting_mode: true         # Enable backtesting mode

# Signal Quality Filters Configuration (enhanced)
signal_quality_filters:
  min_score_threshold: 0.7       # Minimum signal score to consider
  max_correlation_threshold: 0.6 # Maximum correlation between signals
  min_volume_percentile: 60      # Minimum volume percentile
  min_price: 5.0                 # Minimum price for a stock
  max_spread_percent: 0.8        # Maximum bid-ask spread percentage
  min_volatility_percentile: 30  # Minimum volatility percentile
  max_volatility_percentile: 85  # Maximum volatility percentile
  min_regime_weight: 0.4         # Minimum regime weight for a strategy
  max_signals_per_regime: 8      # Maximum signals per market regime
  max_sector_exposure: 0.4       # Maximum sector exposure (as fraction)
  max_signals_per_day: 20        # Maximum signals per day

# Adaptive Position Sizing Configuration (enhanced)
position_sizing_config:
  base_risk_per_trade: 0.02      # Base risk per trade (as fraction of portfolio)
  max_position_size: 0.15        # Maximum position size (as fraction of portfolio)
  min_position_size: 0.01        # Minimum position size (as fraction of portfolio)
  volatility_adjustment: true     # Enable volatility-based position sizing
  signal_strength_adjustment: true # Enable signal strength-based position sizing

# ML-Based Strategy Selection Configuration
ml_strategy_selector:
  ml_lookback_window: 45         # Lookback window for ML training (days)
  ml_min_training_samples: 120   # Minimum training samples required
  ml_retraining_frequency: 5     # Retraining frequency (days)
  ml_feature_columns:            # Features used for ML models
    - vix
    - market_adx
    - trending_strength
    - range_bound_strength
    - volatility_strength
    - regime_change_probability
    - sector_rotation_score
    - breadth_indicator
    - sentiment_score

# Stocks Configuration (optimized parameters)
stocks:
  - symbol: AAPL
    max_position_size: 750
    min_position_size: 20
    max_risk_per_trade_pct: 0.8
    min_volume: 15000
    beta: 1.2
    sector: Technology
    industry: Consumer Electronics
    mean_reversion_params:
      bb_period: 8
      bb_std_dev: 1.2
      rsi_period: 6
      rsi_overbought: 65
      rsi_oversold: 35
      min_reversal_candles: 1
    trend_following_params:
      adx_threshold: 18
      adx_period: 6
      ema_short: 4
      ema_long: 9
    volatility_breakout_params:
      min_squeeze_periods: 2
      bollinger_period: 8
      keltner_period: 8
    gap_trading_params:
      min_gap_pct: 0.6
  
  - symbol: MSFT
    max_position_size: 750
    min_position_size: 20
    max_risk_per_trade_pct: 0.8
    min_volume: 15000
    beta: 1.1
    sector: Technology
    industry: Software
    mean_reversion_params:
      bb_period: 8
      bb_std_dev: 1.2
      rsi_period: 6
      rsi_overbought: 65
      rsi_oversold: 35
      min_reversal_candles: 1
    trend_following_params:
      adx_threshold: 18
      adx_period: 6
      ema_short: 4
      ema_long: 9
    volatility_breakout_params:
      min_squeeze_periods: 2
      bollinger_period: 8
      keltner_period: 8
    gap_trading_params:
      min_gap_pct: 0.6
      
  - symbol: AMZN
    max_position_size: 750
    min_position_size: 20
    max_risk_per_trade_pct: 0.8
    min_volume: 15000
    beta: 1.3
    sector: Consumer Cyclical
    industry: Internet Retail
    mean_reversion_params:
      bb_period: 8
      bb_std_dev: 1.2
      rsi_period: 6
      rsi_overbought: 65
      rsi_oversold: 35
      min_reversal_candles: 1
    trend_following_params:
      adx_threshold: 18
      adx_period: 6
      ema_short: 4
      ema_long: 9
    volatility_breakout_params:
      min_squeeze_periods: 2
      bollinger_period: 8
      keltner_period: 8
    gap_trading_params:
      min_gap_pct: 0.6
      
  - symbol: GOOGL
    max_position_size: 750
    min_position_size: 20
    max_risk_per_trade_pct: 0.8
    min_volume: 15000
    beta: 1.2
    sector: Communication Services
    industry: Internet Content & Information
    mean_reversion_params:
      bb_period: 8
      bb_std_dev: 1.2
      rsi_period: 6
      rsi_overbought: 65
      rsi_oversold: 35
      min_reversal_candles: 1
    trend_following_params:
      adx_threshold: 18
      adx_period: 6
      ema_short: 4
      ema_long: 9
    volatility_breakout_params:
      min_squeeze_periods: 2
      bollinger_period: 8
      keltner_period: 8
    gap_trading_params:
      min_gap_pct: 0.6
      
  - symbol: META
    max_position_size: 750
    min_position_size: 20
    max_risk_per_trade_pct: 0.8
    min_volume: 15000
    beta: 1.4
    sector: Communication Services
    industry: Internet Content & Information
    mean_reversion_params:
      bb_period: 8
      bb_std_dev: 1.2
      rsi_period: 6
      rsi_overbought: 65
      rsi_oversold: 35
      min_reversal_candles: 1
    trend_following_params:
      adx_threshold: 18
      adx_period: 6
      ema_short: 4
      ema_long: 9
    volatility_breakout_params:
      min_squeeze_periods: 2
      bollinger_period: 8
      keltner_period: 8
    gap_trading_params:
      min_gap_pct: 0.6
      
  - symbol: NVDA
    max_position_size: 750
    min_position_size: 20
    max_risk_per_trade_pct: 0.8
    min_volume: 15000
    beta: 1.6
    sector: Technology
    industry: Semiconductors
    mean_reversion_params:
      bb_period: 8
      bb_std_dev: 1.2
      rsi_period: 6
      rsi_overbought: 65
      rsi_oversold: 35
      min_reversal_candles: 1
    trend_following_params:
      adx_threshold: 18
      adx_period: 6
      ema_short: 4
      ema_long: 9
    volatility_breakout_params:
      min_squeeze_periods: 2
      bollinger_period: 8
      keltner_period: 8
    gap_trading_params:
      min_gap_pct: 0.6
      
  - symbol: TSLA
    max_position_size: 750
    min_position_size: 20
    max_risk_per_trade_pct: 0.8
    min_volume: 15000
    beta: 1.8
    sector: Consumer Cyclical
    industry: Auto Manufacturers
    mean_reversion_params:
      bb_period: 8
      bb_std_dev: 1.2
      rsi_period: 6
      rsi_overbought: 65
      rsi_oversold: 35
      min_reversal_candles: 1
    trend_following_params:
      adx_threshold: 18
      adx_period: 6
      ema_short: 4
      ema_long: 9
    volatility_breakout_params:
      min_squeeze_periods: 2
      bollinger_period: 8
      keltner_period: 8
    gap_trading_params:
      min_gap_pct: 0.6
      
  - symbol: JPM
    max_position_size: 750
    min_position_size: 20
    max_risk_per_trade_pct: 0.8
    min_volume: 15000
    beta: 1.0
    sector: Financial Services
    industry: Banks
    mean_reversion_params:
      bb_period: 8
      bb_std_dev: 1.2
      rsi_period: 6
      rsi_overbought: 65
      rsi_oversold: 35
      min_reversal_candles: 1
    trend_following_params:
      adx_threshold: 18
      adx_period: 6
      ema_short: 4
      ema_long: 9
    volatility_breakout_params:
      min_squeeze_periods: 2
      bollinger_period: 8
      keltner_period: 8
    gap_trading_params:
      min_gap_pct: 0.6
      
  - symbol: V
    max_position_size: 750
    min_position_size: 20
    max_risk_per_trade_pct: 0.8
    min_volume: 15000
    beta: 0.9
    sector: Financial Services
    industry: Credit Services
    mean_reversion_params:
      bb_period: 8
      bb_std_dev: 1.2
      rsi_period: 6
      rsi_overbought: 65
      rsi_oversold: 35
      min_reversal_candles: 1
    trend_following_params:
      adx_threshold: 18
      adx_period: 6
      ema_short: 4
      ema_long: 9
    volatility_breakout_params:
      min_squeeze_periods: 2
      bollinger_period: 8
      keltner_period: 8
    gap_trading_params:
      min_gap_pct: 0.6
      
  - symbol: DIS
    max_position_size: 750
    min_position_size: 20
    max_risk_per_trade_pct: 0.8
    min_volume: 15000
    beta: 1.1
    sector: Communication Services
    industry: Entertainment
    mean_reversion_params:
      bb_period: 8
      bb_std_dev: 1.2
      rsi_period: 6
      rsi_overbought: 65
      rsi_oversold: 35
      min_reversal_candles: 1
    trend_following_params:
      adx_threshold: 18
      adx_period: 6
      ema_short: 4
      ema_long: 9
    volatility_breakout_params:
      min_squeeze_periods: 2
      bollinger_period: 8
      keltner_period: 8
    gap_trading_params:
      min_gap_pct: 0.6
