# Fixed Enhanced Alpaca Trading System Configuration
# ------------------------------------------
# This configuration has improved risk management settings to prevent excessive losses

# Overall System Configuration
initial_capital: 100000.0         # Starting capital
max_open_positions: 10           # Maximum positions across all symbols (reduced from 20)
max_positions_per_symbol: 2      # Maximum positions per symbol (reduced from 3)
max_correlated_positions: 5      # Maximum correlated positions (reduced from 8)
max_sector_exposure_pct: 25.0    # Maximum exposure to any sector (reduced from 40%)
max_portfolio_risk_daily_pct: 1.5  # Maximum portfolio risk per day (reduced from 3%)
rebalance_interval: 1d           # Rebalance interval (d=days, h=hours)
data_lookback_days: 60           # Days of historical data to maintain
market_hours_start: '09:30'      # Market open time (EST)
market_hours_end: '16:00'        # Market close time (EST)
debug_mode: true                 # Enable debug mode for more verbose logging

# Data Source Configuration
data_source: ALPACA             # Data source (YAHOO, ALPACA, IB)
api_key: null                   # API key (loaded from credentials file)
api_secret: null                # API secret (loaded from credentials file)

# Strategy Weights (adjusted based on performance)
strategy_weights:
  MeanReversion: 0.20          # Mean reversion strategy weight (reduced from 0.40)
  TrendFollowing: 0.50         # Trend following strategy weight (increased from 0.30)
  VolatilityBreakout: 0.20     # Volatility breakout strategy weight (unchanged)
  GapTrading: 0.10             # Gap trading strategy weight (unchanged)

# Trading Configuration
enable_auto_trading: false     # Enable automated trading
backtesting_mode: true         # Enable backtesting mode

# Signal Quality Filters Configuration (enhanced)
signal_quality_filters:
  min_score_threshold: 0.75      # Minimum signal score to consider (increased from 0.7)
  max_correlation_threshold: 0.5 # Maximum correlation between signals (reduced from 0.6)
  min_volume_percentile: 70      # Minimum volume percentile (increased from 60)
  min_price: 10.0                # Minimum price for a stock (increased from 5.0)
  max_spread_percent: 0.5        # Maximum bid-ask spread percentage (reduced from 0.8)
  min_volatility_percentile: 30  # Minimum volatility percentile
  max_volatility_percentile: 70  # Maximum volatility percentile (reduced from 85)
  min_regime_weight: 0.5         # Minimum regime weight for a strategy (increased from 0.4)
  max_signals_per_regime: 5      # Maximum signals per market regime (reduced from 8)
  max_sector_exposure: 0.25      # Maximum sector exposure (reduced from 0.4)
  max_signals_per_day: 10        # Maximum signals per day (reduced from 20)

# Adaptive Position Sizing Configuration (safer settings)
position_sizing_config:
  base_risk_per_trade: 0.01      # Base risk per trade (reduced from 0.02)
  max_position_size: 0.05        # Maximum position size (reduced from 0.15)
  min_position_size: 0.005       # Minimum position size (reduced from 0.01)
  volatility_adjustment: true    # Enable volatility-based position sizing
  signal_strength_adjustment: true # Enable signal strength-based position sizing

# ML-Based Strategy Selection Configuration
ml_strategy_selector:
  ml_lookback_window: 45         # Lookback window for ML training (days)
  ml_min_training_samples: 120   # Minimum training samples required
  ml_retraining_frequency: 5     # Retraining frequency (days)
  ml_feature_columns:            # Features used for ML models
    - vix
    - market_adx
    - trending_strength
    - range_bound_strength
    - volatility_strength
    - regime_change_probability
    - sector_rotation_score
    - breadth_indicator
    - sentiment_score

# Stocks Configuration (with safer parameters)
stocks:
  - symbol: AAPL
    max_position_size: 250       # Reduced from 750
    min_position_size: 20
    max_risk_per_trade_pct: 0.5  # Reduced from 0.8
    min_volume: 15000
    beta: 1.2
    sector: Technology
    industry: Consumer Electronics
    mean_reversion_params:
      bb_period: 20              # Increased from 8
      bb_std_dev: 2.0            # Increased from 1.2
      rsi_period: 14             # Increased from 6
      rsi_overbought: 70         # Increased from 65
      rsi_oversold: 30           # Decreased from 35
      min_reversal_candles: 2    # Increased from 1
    trend_following_params:
      adx_threshold: 25          # Increased from 18
      adx_period: 14             # Increased from 6
      ema_short: 9               # Increased from 4
      ema_long: 21               # Increased from 9
    volatility_breakout_params:
      min_squeeze_periods: 5     # Increased from 2
      bollinger_period: 20       # Increased from 8
      keltner_period: 20         # Increased from 8
    gap_trading_params:
      min_gap_pct: 1.0           # Increased from 0.6
  
  - symbol: MSFT
    max_position_size: 250       # Reduced from 750
    min_position_size: 20
    max_risk_per_trade_pct: 0.5  # Reduced from 0.8
    min_volume: 15000
    beta: 1.1
    sector: Technology
    industry: Software
    mean_reversion_params:
      bb_period: 20              # Increased from 8
      bb_std_dev: 2.0            # Increased from 1.2
      rsi_period: 14             # Increased from 6
      rsi_overbought: 70         # Increased from 65
      rsi_oversold: 30           # Decreased from 35
      min_reversal_candles: 2    # Increased from 1
    trend_following_params:
      adx_threshold: 25          # Increased from 18
      adx_period: 14             # Increased from 6
      ema_short: 9               # Increased from 4
      ema_long: 21               # Increased from 9
    volatility_breakout_params:
      min_squeeze_periods: 5     # Increased from 2
      bollinger_period: 20       # Increased from 8
      keltner_period: 20         # Increased from 8
    gap_trading_params:
      min_gap_pct: 1.0           # Increased from 0.6
      
  - symbol: AMZN
    max_position_size: 250       # Reduced from 750
    min_position_size: 20
    max_risk_per_trade_pct: 0.5  # Reduced from 0.8
    min_volume: 15000
    beta: 1.3
    sector: Consumer Cyclical
    industry: Internet Retail
    mean_reversion_params:
      bb_period: 20              # Increased from 8
      bb_std_dev: 2.0            # Increased from 1.2
      rsi_period: 14             # Increased from 6
      rsi_overbought: 70         # Increased from 65
      rsi_oversold: 30           # Decreased from 35
      min_reversal_candles: 2    # Increased from 1
    trend_following_params:
      adx_threshold: 25          # Increased from 18
      adx_period: 14             # Increased from 6
      ema_short: 9               # Increased from 4
      ema_long: 21               # Increased from 9
    volatility_breakout_params:
      min_squeeze_periods: 5     # Increased from 2
      bollinger_period: 20       # Increased from 8
      keltner_period: 20         # Increased from 8
    gap_trading_params:
      min_gap_pct: 1.0           # Increased from 0.6
      
  - symbol: GOOGL
    max_position_size: 250       # Reduced from 750
    min_position_size: 20
    max_risk_per_trade_pct: 0.5  # Reduced from 0.8
    min_volume: 15000
    beta: 1.2
    sector: Communication Services
    industry: Internet Content & Information
    mean_reversion_params:
      bb_period: 20              # Increased from 8
      bb_std_dev: 2.0            # Increased from 1.2
      rsi_period: 14             # Increased from 6
      rsi_overbought: 70         # Increased from 65
      rsi_oversold: 30           # Decreased from 35
      min_reversal_candles: 2    # Increased from 1
    trend_following_params:
      adx_threshold: 25          # Increased from 18
      adx_period: 14             # Increased from 6
      ema_short: 9               # Increased from 4
      ema_long: 21               # Increased from 9
    volatility_breakout_params:
      min_squeeze_periods: 5     # Increased from 2
      bollinger_period: 20       # Increased from 8
      keltner_period: 20         # Increased from 8
    gap_trading_params:
      min_gap_pct: 1.0           # Increased from 0.6
      
  - symbol: META
    max_position_size: 250       # Reduced from 750
    min_position_size: 20
    max_risk_per_trade_pct: 0.5  # Reduced from 0.8
    min_volume: 15000
    beta: 1.4
    sector: Communication Services
    industry: Internet Content & Information
    mean_reversion_params:
      bb_period: 20              # Increased from 8
      bb_std_dev: 2.0            # Increased from 1.2
      rsi_period: 14             # Increased from 6
      rsi_overbought: 70         # Increased from 65
      rsi_oversold: 30           # Decreased from 35
      min_reversal_candles: 2    # Increased from 1
    trend_following_params:
      adx_threshold: 25          # Increased from 18
      adx_period: 14             # Increased from 6
      ema_short: 9               # Increased from 4
      ema_long: 21               # Increased from 9
    volatility_breakout_params:
      min_squeeze_periods: 5     # Increased from 2
      bollinger_period: 20       # Increased from 8
      keltner_period: 20         # Increased from 8
    gap_trading_params:
      min_gap_pct: 1.0           # Increased from 0.6
