api_key: null
api_secret: null
backtesting_mode: true
data_lookback_days: 45  # Increased from 30 to provide more historical context
data_source: YAHOO
debug_mode: true
enable_auto_trading: false
initial_capital: 100000.0
market_hours_end: '16:00'
market_hours_start: 09:30
max_correlated_positions: 5
max_open_positions: 15  # Increased from 10 to allow more diversification
max_portfolio_risk_daily_pct: 1.5  # Reduced from 2.0 for better risk management
max_positions_per_symbol: 2
max_sector_exposure_pct: 25.0  # Reduced from 30.0 for better sector diversification
ml_strategy_selector:
  max_depth: 6  # Increased from 5 for more complex decision trees
  ml_lookback_window: 20  # Increased from 15 for better pattern recognition
  ml_min_training_samples: 75  # Increased from 50 for more robust model training
  ml_retraining_frequency: 2  # Reduced from 3 for more frequent model updates
  n_estimators: 100  # Increased from 50 for better ensemble learning
position_sizing_config:
  base_risk_per_trade: 0.004  # Reduced from 0.005 for more conservative position sizing
  max_position_size: 0.04  # Reduced from 0.05 to limit exposure per position
  min_position_size: 0.002
  signal_strength_adjustment: true
  volatility_adjustment: true
  profit_target_adjustment: true  # New parameter to adjust take-profit based on market conditions
  dynamic_stop_loss: true  # New parameter to implement trailing stops
rebalance_interval: 1d
signal_quality_filters:
  max_correlation_threshold: 0.4  # Reduced from 0.5 for less correlated positions
  max_signals_per_day: 7  # Increased from 5 to capture more opportunities
  min_regime_weight: 0.25  # Increased from 0.2 for stronger regime alignment
  min_score_threshold: 0.6  # Increased from 0.5 for higher quality signals
  min_volume_percentile: 40  # Increased from 30 for better liquidity
  max_volatility_percentile: 85  # Added to avoid extremely volatile stocks
  min_price: 5.0  # Added minimum price filter
  max_spread_percent: 0.8  # Added maximum spread percentage
strategy_weights:
  MeanReversion: 0.40  # Increased weight for the best performing strategy
  TrendFollowing: 0.25
  VolatilityBreakout: 0.20
  GapTrading: 0.15
volatility_breakout_params:  # Global parameters for volatility breakout
  bb_period: 15
  bb_std_dev: 1.8
  keltner_period: 15
  keltner_factor: 1.3
  min_squeeze_periods: 8
  volume_threshold: 1.8
stocks:
- beta: 1.2
  gap_trading_params:
    min_gap_pct: 0.5
  industry: Consumer Electronics
  max_position_size: 500
  max_risk_per_trade_pct: 0.5
  mean_reversion_params:
    bb_period: 10
    bb_std_dev: 1.0
    min_reversal_candles: 1
    rsi_overbought: 60
    rsi_oversold: 40
    rsi_period: 7
  min_position_size: 10
  min_volume: 10000
  sector: Technology
  symbol: AAPL
  volatility_breakout_params:
    bb_period: 15
    bb_std_dev: 1.8
    keltner_factor: 1.3
    keltner_period: 15
    min_squeeze_periods: 8
    volume_threshold: 1.8
- beta: 1.5
  gap_trading_params:
    min_gap_pct: 0.6
  industry: Internet Retail
  max_position_size: 300
  max_risk_per_trade_pct: 0.5
  mean_reversion_params:
    bb_period: 12
    bb_std_dev: 1.2
    min_reversal_candles: 2
    rsi_overbought: 65
    rsi_oversold: 35
    rsi_period: 8
  min_position_size: 10
  min_volume: 15000
  sector: Consumer Cyclical
  symbol: AMZN
- beta: 1.3
  gap_trading_params:
    min_gap_pct: 0.5
  industry: Internet Content & Information
  max_position_size: 200
  max_risk_per_trade_pct: 0.5
  mean_reversion_params:
    bb_period: 10
    bb_std_dev: 1.1
    min_reversal_candles: 2
    rsi_overbought: 62
    rsi_oversold: 38
    rsi_period: 7
  min_position_size: 10
  min_volume: 12000
  sector: Communication Services
  symbol: GOOGL
  volatility_breakout_params:
    bb_period: 18
    bb_std_dev: 2.0
    keltner_factor: 1.4
    keltner_period: 18
    min_squeeze_periods: 10
    volume_threshold: 2.0
- beta: 1.8
  gap_trading_params:
    min_gap_pct: 1.0
  industry: Auto Manufacturers
  max_position_size: 100
  max_risk_per_trade_pct: 0.4
  mean_reversion_params:
    bb_period: 8
    bb_std_dev: 1.5
    min_reversal_candles: 3
    rsi_overbought: 70
    rsi_oversold: 30
    rsi_period: 6
  min_position_size: 5
  min_volume: 20000
  sector: Consumer Cyclical
  symbol: TSLA
