api_key: null
api_secret: null
backtesting_mode: true
data_lookback_days: 30
data_source: YAHOO
debug_mode: true
enable_auto_trading: false
initial_capital: 100000.0
market_hours_end: '16:00'
market_hours_start: 09:30
max_correlated_positions: 5
max_open_positions: 10
max_portfolio_risk_daily_pct: 2.0
max_positions_per_symbol: 2
max_sector_exposure_pct: 30.0
ml_strategy_selector:
  max_depth: 5
  ml_lookback_window: 15
  ml_min_training_samples: 50
  ml_retraining_frequency: 3
  n_estimators: 50
position_sizing_config:
  base_risk_per_trade: 0.005
  max_position_size: 0.05
  min_position_size: 0.002
  signal_strength_adjustment: true
  volatility_adjustment: true
rebalance_interval: 1d
signal_quality_filters:
  max_correlation_threshold: 0.5
  max_signals_per_day: 5
  min_regime_weight: 0.2
  min_score_threshold: 0.5
  min_volume_percentile: 30
stocks:
- beta: 1.2
  gap_trading_params:
    min_gap_pct: 0.5
  industry: Consumer Electronics
  max_position_size: 500
  max_risk_per_trade_pct: 0.5
  mean_reversion_params:
    bb_period: 10
    bb_std_dev: 1.0
    min_reversal_candles: 1
    rsi_overbought: 60
    rsi_oversold: 40
    rsi_period: 7
  min_position_size: 10
  min_volume: 10000
  sector: Technology
  symbol: AAPL
  trend_following_params:
    adx_period: 7
    adx_threshold: 15
    ema_long: 10
    ema_short: 5
  volatility_breakout_params:
    bollinger_period: 10
    keltner_period: 10
    min_squeeze_periods: 3
- beta: 1.1
  gap_trading_params:
    min_gap_pct: 0.5
  industry: Software
  max_position_size: 500
  max_risk_per_trade_pct: 0.5
  mean_reversion_params:
    bb_period: 10
    bb_std_dev: 1.0
    min_reversal_candles: 1
    rsi_overbought: 60
    rsi_oversold: 40
    rsi_period: 7
  min_position_size: 10
  min_volume: 10000
  sector: Technology
  symbol: MSFT
  trend_following_params:
    adx_period: 7
    adx_threshold: 15
    ema_long: 10
    ema_short: 5
  volatility_breakout_params:
    bollinger_period: 10
    keltner_period: 10
    min_squeeze_periods: 3
- beta: 1.3
  gap_trading_params:
    min_gap_pct: 0.5
  industry: Internet Services
  max_position_size: 500
  max_risk_per_trade_pct: 0.5
  mean_reversion_params:
    bb_period: 10
    bb_std_dev: 1.0
    min_reversal_candles: 1
    rsi_overbought: 60
    rsi_oversold: 40
    rsi_period: 7
  min_position_size: 10
  min_volume: 10000
  sector: Technology
  symbol: GOOGL
  trend_following_params:
    adx_period: 7
    adx_threshold: 15
    ema_long: 10
    ema_short: 5
  volatility_breakout_params:
    bollinger_period: 10
    keltner_period: 10
    min_squeeze_periods: 3
- beta: 1.4
  gap_trading_params:
    min_gap_pct: 0.5
  industry: E-Commerce
  max_position_size: 200
  max_risk_per_trade_pct: 0.5
  mean_reversion_params:
    bb_period: 10
    bb_std_dev: 1.0
    min_reversal_candles: 1
    rsi_overbought: 60
    rsi_oversold: 40
    rsi_period: 7
  min_position_size: 5
  min_volume: 10000
  sector: Consumer Discretionary
  symbol: AMZN
  trend_following_params:
    adx_period: 7
    adx_threshold: 15
    ema_long: 10
    ema_short: 5
  volatility_breakout_params:
    bollinger_period: 10
    keltner_period: 10
    min_squeeze_periods: 3
- beta: 1.2
  gap_trading_params:
    min_gap_pct: 0.5
  industry: Social Media
  max_position_size: 300
  max_risk_per_trade_pct: 0.5
  mean_reversion_params:
    bb_period: 10
    bb_std_dev: 1.0
    min_reversal_candles: 1
    rsi_overbought: 60
    rsi_oversold: 40
    rsi_period: 7
  min_position_size: 5
  min_volume: 10000
  sector: Technology
  symbol: META
  trend_following_params:
    adx_period: 7
    adx_threshold: 15
    ema_long: 10
    ema_short: 5
  volatility_breakout_params:
    bollinger_period: 10
    keltner_period: 10
    min_squeeze_periods: 3
- beta: 1.5
  gap_trading_params:
    min_gap_pct: 0.5
  industry: Semiconductors
  max_position_size: 300
  max_risk_per_trade_pct: 0.5
  mean_reversion_params:
    bb_period: 10
    bb_std_dev: 1.0
    min_reversal_candles: 1
    rsi_overbought: 60
    rsi_oversold: 40
    rsi_period: 7
  min_position_size: 5
  min_volume: 10000
  sector: Technology
  symbol: NVDA
  trend_following_params:
    adx_period: 7
    adx_threshold: 15
    ema_long: 10
    ema_short: 5
  volatility_breakout_params:
    bollinger_period: 10
    keltner_period: 10
    min_squeeze_periods: 3
- beta: 1.4
  gap_trading_params:
    min_gap_pct: 1.0
  industry: Semiconductors
  max_position_size: 400
  max_risk_per_trade_pct: 0.5
  mean_reversion_params:
    bb_std_dev: 1.5
    rsi_overbought: 65
    rsi_oversold: 35
  min_position_size: 10
  min_volume: 10000
  sector: Technology
  symbol: AMD
  trend_following_params:
    adx_threshold: 20
  volatility_breakout_params:
    min_squeeze_periods: 6
- beta: 1.8
  gap_trading_params:
    min_gap_pct: 1.0
  industry: Auto Manufacturers
  max_position_size: 100
  max_risk_per_trade_pct: 0.5
  mean_reversion_params:
    bb_std_dev: 1.5
    rsi_overbought: 65
    rsi_oversold: 35
  min_position_size: 5
  min_volume: 10000
  sector: Consumer Cyclical
  symbol: TSLA
  trend_following_params:
    adx_threshold: 20
  volatility_breakout_params:
    min_squeeze_periods: 6
- beta: 1.1
  gap_trading_params:
    min_gap_pct: 1.0
  industry: Banks
  max_position_size: 400
  max_risk_per_trade_pct: 0.4
  mean_reversion_params:
    bb_std_dev: 1.5
    rsi_overbought: 65
    rsi_oversold: 35
  min_position_size: 10
  min_volume: 5000
  sector: Financial Services
  symbol: JPM
  trend_following_params:
    adx_threshold: 20
  volatility_breakout_params:
    min_squeeze_periods: 6
- beta: 1.0
  gap_trading_params:
    min_gap_pct: 1.0
  industry: Entertainment
  max_position_size: 400
  max_risk_per_trade_pct: 0.4
  mean_reversion_params:
    bb_std_dev: 1.5
    rsi_overbought: 65
    rsi_oversold: 35
  min_position_size: 10
  min_volume: 5000
  sector: Communication Services
  symbol: DIS
  trend_following_params:
    adx_threshold: 20
  volatility_breakout_params:
    min_squeeze_periods: 6
- beta: 1.0
  gap_trading_params:
    min_gap_pct: 1.0
  industry: S&P 500
  max_position_size: 500
  max_risk_per_trade_pct: 0.3
  mean_reversion_params:
    bb_std_dev: 1.5
    rsi_overbought: 65
    rsi_oversold: 35
  min_position_size: 10
  min_volume: 5000
  sector: Index
  symbol: SPY
  trend_following_params:
    adx_threshold: 20
  volatility_breakout_params:
    min_squeeze_periods: 6
- beta: 0.9
  gap_trading_params:
    min_gap_pct: 1.0
  industry: Credit Services
  max_position_size: 400
  max_risk_per_trade_pct: 0.3
  mean_reversion_params:
    bb_std_dev: 1.5
    rsi_overbought: 65
    rsi_oversold: 35
  min_position_size: 10
  min_volume: 5000
  sector: Financial Services
  symbol: V
  trend_following_params:
    adx_threshold: 20
  volatility_breakout_params:
    min_squeeze_periods: 6
strategy_weights:
  GapTrading: 0.25
  MeanReversion: 0.25
  TrendFollowing: 0.25
  VolatilityBreakout: 0.25
